#DROP DATABASE geodb;
CREATE DATABASE IF NOT EXISTS geodb;
USE geodb;

DROP TABLE IF EXISTS Regions;
CREATE TABLE Regions (
  num INT(10) NOT NULL,
  nom VARCHAR(50) NULL,
  PRIMARY KEY (num),
  INDEX num (num)
);

INSERT INTO Regions(num,nom)
VALUES (1, 'Ile de France'),
  (2, 'Alsace'),
  (3, 'Aquitaine'),
  (4, 'Auvergne'),
  (5, 'Bourgogne'),
  (6, 'Bretagne'),
  (7, 'Centre'),
  (8, 'Champagne Ardennes'),
  (9, 'Franche Comté'),
  (10, 'Languedoc Roussillon'),
  (11, 'Limousin'),
  (12, 'Lorraine'),
  (13, 'Midi Pyrénées'),
  (14, 'Nord Pas de Calais'),
  (15, 'Basse Normandie'),
  (16, 'Haute Normandie'),
  (17, 'Pays de Loire'),
  (18, 'Picardie'),
  (19, 'Poitou Charentes'),
  (20, 'Provence Côte d\'Azur'),
  (21, 'Rhone Alpes'),
  (22, 'Corse');



DROP TABLE IF EXISTS Departements;
CREATE TABLE Departements (
  num INT(10) NOT NULL,
  numRegion INT(10) NULL,
  nom VARCHAR(50) NULL,
  prefecture VARCHAR(50) NULL,
  PRIMARY KEY (num),
  INDEX num (num),
  INDEX numRegion ( numRegion)
);

ALTER TABLE Departements ADD CONSTRAINT Un_Dep_a_une_region_valide FOREIGN KEY (numRegion) REFERENCES Regions (num);


INSERT INTO Departements(num,numRegion,nom,prefecture)
VALUES (75, 1, 'Paris', 'Paris'),
  (92, 1, 'Hauts de Seine', 'Nanterre'),
  (93, 1, 'Seine St Denis', 'Bobigny'),
  (94, 1, 'Val de Marne', 'Créteil'),
  (95, 1, 'Val d\'Oise', 'Pontoise'),
  (78, 1, 'Yvelines', 'Versailles'),
  (91, 1, 'Essones', 'Evry'),
  (77, 1, 'Seine et Marne', 'Melun'),
  (67, 2, 'Bas Rhin', 'Strasbourg'),
  (68, 2, 'Haut Rhin', 'Colmar'),
  (33, 3, 'Gironde', 'Bordeaux'),
  (24, 3, 'Dordogne', 'Périgueux'),
  (40, 3, 'Landes', 'Mont-de-Marsan'),
  (47, 3, 'Lot et Garonne', 'Agen'),
  (64, 3, 'Pyrénées Atlantiques', 'Pau'),
  (3, 4, 'Allier', 'Moulins'),
  (63, 4, 'Puy de dôme', 'Clermont Ferrand'),
  (15, 4, 'Cantal', 'Aurillac'),
  (43, 4, 'Haute Loire', 'Le Puy-en-Velay'),
  (89, 5, 'Yonne', 'Auxerre'),
  (21, 5, 'Côte d\'or', 'Dijon'),
  (58, 5, 'Nièvre', 'Nevers'),
  (71, 5, 'Saône et Loire', 'Mâcon'),
  (29, 6, 'Finistère', 'Quimper'),
  (22, 6, 'Côtes d\'Armor', 'Saint Brieuc'),
  (56, 6, 'Morbihan', 'Vannes'),
  (35, 6, 'Ile et Vilaine', 'Rennes'),
  (28, 7, 'Eure et Loire', 'Chartres'),
  (41, 7, 'Loir et Cher', 'Blois'),
  (45, 7, 'Loiret', 'Orléans'),
  (37, 7, 'Indre et Loire', 'Tours'),
  (36, 7, 'Indre', 'Châteauroux'),
  (18, 7, 'Cher', 'Bourges'),
  (8, 8, 'Ardennes', 'Charleville-Mezières'),
  (51, 8, 'Marne', 'Châlons-en-Champagne'),
  (10, 8, 'Aube', 'Troyes'),
  (52, 8, 'Haute Marne', 'Chaumont'),
  (70, 9, 'Haute Saône', 'Vesoul'),
  (90, 9, 'Territoire de Belfort', 'Belfort'),
  (25, 9, 'Doubs', 'Besançon'),
  (39, 9, 'Jura', 'Lons-le-Saunier'),
  (48, 10, 'Lozère', 'Mende'),
  (30, 10, 'Gard', 'Nîmes'),
  (34, 10, 'Hérault', 'Montpellier'),
  (11, 10, 'Aude', 'Carcassonne'),
  (66, 10, 'Pyrénées Orientales', 'Perpignan'),
  (23, 11, 'Creuse', 'Guéret'),
  (87, 11, 'Haute Vienne', 'Limoges'),
  (19, 11, 'Corrèze', 'Tulles'),
  (55, 12, 'Meuse', 'Bar le Duc'),
  (54, 12, 'Meurthe et Moselle', 'Nancy'),
  (57, 12, 'Moselle', 'Metz'),
  (88, 12, 'Vosges', 'Epinal'),
  (46, 13, 'Lot', 'Cahors'),
  (82, 13, 'Tarn et Garonne', 'Montauban'),
  (32, 13, 'Gers', 'Auch'),
  (65, 13, 'Haute Pyrénées', 'Tarbes'),
  (31, 13, 'Haute Garonne', 'Toulouse'),
  (9, 13, 'Ariège', 'Foix'),
  (81, 13, 'Tarn', 'Albi'),
  (12, 13, 'Aveyron', 'Rodez'),
  (59, 14, 'Nord', 'Lille'),
  (62, 14, 'Pas de Calais', 'Arras'),
  (14, 15, 'Calvados', 'Caen'),
  (50, 15, 'Manche', 'Saint Lô'),
  (61, 15, 'Orne', 'Alençon'),
  (76, 16, 'Seine Maritime', 'Rouen'),
  (27, 16, 'Eure', 'Evreux'),
  (53, 17, 'Mayenne', 'Laval'),
  (72, 17, 'Sarthe', 'Le Mans'),
  (44, 17, 'Loire Atlantique', 'Nantes'),
  (49, 17, 'Maine et Loire', 'Angers'),
  (85, 17, 'Vendée', 'La Roche-sur-Yon'),
  (80, 18, 'Somme', 'Amiens'),
  (60, 18, 'Oise', 'Beauvais'),
  (2, 18, 'Aisne', 'Laon'),
  (79, 19, 'Deux Sèvres', 'Niort'),
  (86, 19, 'Vienne', 'Poitiers'),
  (17, 19, 'Charente Maritime', 'La Rochelle'),
  (16, 19, 'Charente', 'Angoulême'),
  (5, 20, 'Hautes Alpes', 'Gap'),
  (4, 20, 'Alpes de Haute Provence', 'Digne'),
  (84, 20, 'Vaucluse', 'Avignon'),
  (13, 20, 'Bouches du Rhônes', 'Marseille'),
  (83, 20, 'Var', 'Toulon'),
  (6, 20, 'Alpes Maritimes', 'Nice'),
  (42, 21, 'Loire', 'Saint Etienne'),
  (69, 21, 'Rhône', 'Lyon'),
  (1, 21, 'Ain', 'Bourg-en-Bresse'),
  (74, 21, 'Haute Savoie', 'Annecy'),
  (73, 21, 'Savoie', 'Chambéry'),
  (38, 21, 'Isère', 'Grenoble'),
  (26, 21, 'Drôme', 'Valence'),
  (7, 21, 'Ardèche', 'Privas'),
  (20, 22, 'Corse (2A:Sud,2B:Haute)', 'Bastia_Ajaccio');


show tables;

