
package tp.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculateur", targetNamespace = "http://service.tp/")

public interface Calculateur {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addition", targetNamespace = "http://service.tp/", className = "tp.service.Addition")
    @ResponseWrapper(localName = "additionResponse", targetNamespace = "http://service.tp/", className = "tp.service.AdditionResponse")
    public double addition(
        @WebParam(name = "a", targetNamespace = "")
        double a,
        @WebParam(name = "b", targetNamespace = "")
        double b);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuteur", targetNamespace = "http://service.tp/", className = "tp.service.GetAuteur")
    @ResponseWrapper(localName = "getAuteurResponse", targetNamespace = "http://service.tp/", className = "tp.service.GetAuteurResponse")
    public String getAuteur();

    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplication", targetNamespace = "http://service.tp/", className = "tp.service.Multiplication")
    @ResponseWrapper(localName = "multiplicationResponse", targetNamespace = "http://service.tp/", className = "tp.service.MultiplicationResponse")
    public double multiplication(
        @WebParam(name = "a", targetNamespace = "")
        double a,
        @WebParam(name = "b", targetNamespace = "")
        double b);

}
