
package fr.afcepf.al28.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TvaServiceImplService", targetNamespace = "http://service.al28.afcepf.fr/", wsdlLocation = "http://localhost:8081/serviceTva?wsdl")
public class TvaServiceImplService
    extends Service
{

    private final static URL TVASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TVASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TVASERVICEIMPLSERVICE_QNAME = new QName("http://service.al28.afcepf.fr/", "TvaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/serviceTva?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TVASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TVASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TvaServiceImplService() {
        super(__getWsdlLocation(), TVASERVICEIMPLSERVICE_QNAME);
    }

    public TvaServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TVASERVICEIMPLSERVICE_QNAME, features);
    }

    public TvaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TVASERVICEIMPLSERVICE_QNAME);
    }

    public TvaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TVASERVICEIMPLSERVICE_QNAME, features);
    }

    public TvaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TvaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TvaService
     */
    @WebEndpoint(name = "TvaServiceImplPort")
    public TvaService getTvaServiceImplPort() {
        return super.getPort(new QName("http://service.al28.afcepf.fr/", "TvaServiceImplPort"), TvaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TvaService
     */
    @WebEndpoint(name = "TvaServiceImplPort")
    public TvaService getTvaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.al28.afcepf.fr/", "TvaServiceImplPort"), TvaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TVASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TVASERVICEIMPLSERVICE_EXCEPTION;
        }
        return TVASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
