
package fr.afcepf.al28.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TvaService", targetNamespace = "http://service.al28.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TvaService {


    /**
     * 
     * @param tauxPct
     * @param ht
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ttc", targetNamespace = "http://service.al28.afcepf.fr/", className = "fr.afcepf.al28.service.Ttc")
    @ResponseWrapper(localName = "ttcResponse", targetNamespace = "http://service.al28.afcepf.fr/", className = "fr.afcepf.al28.service.TtcResponse")
    @Action(input = "http://service.al28.afcepf.fr/TvaService/ttcRequest", output = "http://service.al28.afcepf.fr/TvaService/ttcResponse")
    public Double ttc(
        @WebParam(name = "ht", targetNamespace = "")
        Double ht,
        @WebParam(name = "tauxPct", targetNamespace = "")
        Double tauxPct);

    /**
     * 
     * @param tauxPct
     * @param ht
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tva", targetNamespace = "http://service.al28.afcepf.fr/", className = "fr.afcepf.al28.service.Tva")
    @ResponseWrapper(localName = "tvaResponse", targetNamespace = "http://service.al28.afcepf.fr/", className = "fr.afcepf.al28.service.TvaResponse")
    @Action(input = "http://service.al28.afcepf.fr/TvaService/tvaRequest", output = "http://service.al28.afcepf.fr/TvaService/tvaResponse")
    public Double tva(
        @WebParam(name = "ht", targetNamespace = "")
        Double ht,
        @WebParam(name = "tauxPct", targetNamespace = "")
        Double tauxPct);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuteur", targetNamespace = "http://service.al28.afcepf.fr/", className = "fr.afcepf.al28.service.GetAuteur")
    @ResponseWrapper(localName = "getAuteurResponse", targetNamespace = "http://service.al28.afcepf.fr/", className = "fr.afcepf.al28.service.GetAuteurResponse")
    @Action(input = "http://service.al28.afcepf.fr/TvaService/getAuteurRequest", output = "http://service.al28.afcepf.fr/TvaService/getAuteurResponse")
    public String getAuteur();

}
